flux-framework/flux-docs

quickstart.rst

- Updates .rst to match recent updates on .io
- Finishes work started in PR #8 (copying http://flux-framework.org/docs/quickstart/ to this repo)
- Incorporates @cmoussa1 edits from https://github.com/flux-framework/flux-framework.github.io/pull/35 (e.g., Python version, `hwloc` examples)
- Addresses one task in https://github.com/flux-framework/flux-framework.github.io/issues/36
- Also fixes a couple of minor spelling and punctuation issues, plus adds a link to Slurm repo

quickstart.rst: Update with latest version of content

---

contributing.rst

- Resolves issue #1
- Finishes work started in PR #7 (copying http://flux-framework.org/docs/contributing/ to this repo)
- Addresses one task in https://github.com/flux-framework/flux-framework.github.io/issues/36
- Updates/revises content based on discussions in issue #1 and PR #7

contributing.rst: Update with team suggestions

---

.github/workflows/main.yml
.mergify.yml

@grondo: any idea how to add a list to the `approved-reviews-by` condition?  I attempted to use yaml arrays, but the mergify validation (`curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate`) rejects it.
Both `- approved-reviews-by=[@flux-framework/core,@flux-framework/docs]` and
```yaml
- approved-reviews-by=
- @flux-framework/core 
- @flux-framework/docs
```
are rejected.

mergify: add config yaml

---

index.rst

Link to the new rfc index page.

index: link to rfc index

---

faqs.rst
index.rst

Added two question and answer pairs and
added to table of contents.

add faqs page

---

adminguide.rst

Bring most of the 0.21.0 warnings forward to 0.22.0.
Change the flux-keygen usage and CURVE cert path.
Add curve_cert to [bootstrap] configuration.
Change exclusions to use a hostlist.
Change drain to use a hostlist and use 'flux resource drain' with
no arguments to list drained nodes instead of 'flux resource status'.

adminguide: update for flux-core release 0.22.0

---

adminguide.rst

I noticed a couple of minor errors in the admin guide, so here are fixes.

admin guide: minor fixes

---

coral2.rst
index.rst
spell.en.pws

Basic build and usage instructions for Flux on RZNevada and Perlmutter.

Add coral2/Shasta build and usage instructions

---

coral.rst

Fix Issue #48 per @rcarson3's request.

coral: how to run with specific resource set and affinity

---

adminguide.rst

This is a first draft of a section for the Administrator's Guide describing how to configure job-manager prolog and epilog, and how to use the included `flux perilog-run` command to run a per-rank prolog/epilog as root if required.

adminguide: document job-manager prolog and epilog

---

adminguide.rst

Here are some updates to the Admin Guide to go with the upcoming flux-core 0.36 release.

adminguide: update for flux-core 0.36.0

---

adminguide.rst
spell.en.pws

This is a WIP which adds documentation of a couple new features in the flux-core v0.38.0 release.
Just parking this here for now in case someone wants to correct, amend, emend, or expand on these two new sections thus far.
I guess we should also update all the "notes" to reference the new release as well.

adminguide: updates for v0.38.0

---

adminguide.rst

This PR switches the admin config file examples over to using one big example file (for each of the three config spaces) rather than a lot of little files that might be annoying to sys admins.
The examples are not all-inclusive.  accounting, prolog/epilog, and validator configs are still presented in separate "add on" sections.  I did do some re-titling of sections and tweaked the header level in some cases.
Maybe give the rendered version a read and see if it's any better?   I'm not hard over on this change, but I do think it might be a little better than before.

adminguide: use single TOML files for examples

---

adminguide.rst

Here are just a few small improvements to the the Admin Guide.

admin guide: minor improvements

---

adminguide.rst

Here are some adminguide updates for the upcoming 0.39.0 release.  Feel free to push directly to this PR.  I'll be offline most of the day today.

adminguide: update for 0.39

---

adminguide.rst

@woodard was setting up a Flux system instance at home and had some feedback while going through the Admin Guide. This PR includes fixes related to that feedback. I've also updated the version references from 0.40.0 to 0.41.0.

adminguide: updates based on user feedback

---

faqs.rst

After the most recent Flux tutorial, a user asked if there was an equivalent to Slurm's `--overcommit` option, which can be used to run more than one task per allocated core.
It seemed like a good question with multiple answers in Flux (at least currently). So I've added an FAQ entry.

faqs: add faq about overcommitting resources

---

faqs.rst

Problem: the "Why is Flux not discovering and managing all of the resources
on the system/node?" question is overly broad and doesn't explain Flux's
behavior very well.
Focus the question on missing nvidia GPUs and explain in more detail how
that problem can manifest itself.
Drop the bit about "srun --mpibind=off" and "jsrun --bind=none" since
that appears to be answering a different question?

faqs: split missing resources question into two questoins

---

adminguide.rst

Here are a few updates to cover changes in the flux-core 0.43 release.

adminguide: update for flux-core-0.43

---

coral.rst

Now that we have the LSF URI resolver, we should add some documentation so users can take advantage of its utility.
We should probably wait until we release & tag flux-core@0.42.0 and get that built on BlueOS to merge this.

docs: add information on running Flux interactively on CORAL

---

faqs.rst

This is some general cleanup of the faqs page, and entry additions.

faqs: cleanup, add new entries

---

adminguide.rst

This adds a tiny bit to the Queues section and a new Policy Limits section.

adminguide: improve Queues section, add Limits section

---

adminguide.rst

Problem: system administrators need to be aware of how Flux security works.
Add an overview subsection on Flux security to the admin guide.

adminguide: add security section

---

faqs.rst
spell.en.pws

Problem: people want to know how to type a fancy f.
Add some instructions.
Feel free to push additional info here (anybody program a ƒ key macro?)

faqs: add how to input unicode U+0192

---

adminguide.rst

This makes some updates to the admin guide for 0.45.

adminguide: update for flux-core 0.45.0 release

---

conf.py
requirements.txt

Problem: the search is borked on readthedocs. 
Solution: It was suggested to remove these two modules to start.
https://github.com/jbms/sphinx-immaterial/issues/208
If I remember there is a readthedocs preview? We should be able to test quickly with these changes to see if the bug is resolved!
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

first attempt to fix search bug

---

faqs.rst
includes/comparison-table.html
includes/comparison-table.rst
tables/comparison-table.rst

This is a WIP! I have a css/javascript bug somewhere that the last few rows are missing colors, but wanted to share the WIP for quick feedback, etc.
Unless I embedded some html table library to customize this, I couldn't find a way for the simple list-table in rst to support having full width rows every once in a while, so I opted for three separate tables (and I think it looks OK?)  I'm also planning on adding some text that guides the reader to the right places if they want to suggest a feature to add, or point out we are wrong about something.
Finally, note that the same code renders on its own page (above) and the FAQ (below)
Here is the original png for comparison.
I'm going for my run because it's been a day, but I'll be back and hopefully have more patience for JavaScript after …

Add manager comparison table

---

projects.rst

This will add a reference to dyad on the projects page! 
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

add reference to dyad in projects

---

README.md

README.md: add release number

---

guides/admin-guide.rst

We haven't updated the admin guide in a while, so I made a pass through it.

admin-guide: update examples etc for flux-core 0.50.0 release

---

faqs.rst

Problem: some of the mpi/pmi info in the FAQ is outdated.
Update pmi and mpi options.

faq: update MPI/PMI debug info

---

faqs.rst
guides/learning_guide.rst
includes/comparison-table.rst
jobs/batch.rst
jobs/debugging.rst
spell.en.pws
tutorials/commands/ssh-across-clusters.rst

https://slurm.schedmd.com/faq.html#acronym

Use preferred capitalization of "Slurm"
