index.rst, quickstart.rst
Duplicates http://flux-framework.org/docs/quickstart/ (which I will delete after this page is published). I also updated index.rst TOC so this and contributing.rst will show up. Quickstart contains a link to the Build Prerequisites page (http://flux-framework.org/docs/requirements/), which I will update when I move that over to .rst too.
=> New quickstart.rst file

contributing.rst
This file includes everything from http://flux-framework.org/docs/contributing/ (which I will delete after this page is published) plus additional text and links to flesh out the contributing guidelines a bit more. There's more to do (see issue #1, which is NOT fully resolved by this PR), but I wanted something we could to start with.
=> New contributing.rst file

README.md
closes #6
I've left out any specific virtualenv stuff and instead point users at some web documentation.
=> readme: correct pip install list

quickstart.rst
From issue #14: 
> After the most recent release (i.e., in current master), the flux module command lost the --rank argument, and the flux job list command moved from being a "porcelain" command to being a "plumbing" command. It has been replaced by "flux jobs".
This PR addresses #14 and updates the following commands to reflect the changes in [flux-framework/flux-core](https://github.com/flux-framework/flux-core), specifically the drop of `--rank` from `flux module list` and the introduction of `flux jobs`, the new job listing tool.
=> quickstart: Update 'flux module', 'flux job list' usage

quickstart.rst
Some examples used `src/cmd/flux`, assuming the user was in the flux-core source directory/repo.  This assumption no longer holds with the flux-sched install instructions.
As @grondo pointed out in #23, there is no mention of `flux keygen` currently.
=> quickstart: add `flux-keygen` and remove relative paths

quickstart.rst
Update flux-sched instructions now that `PKG_CONFIG_PATH` and `PYTHON_VERSION` are not required to build against side-installed flux-core.
=> quickstart.rst: update flux-sched build instructions

.gitmodules
We will be switching to using [RTD Subprojects](https://docs.readthedocs.io/en/stable/subprojects.html) instead of git submodules.
=> :heavy_minus_sign: removed flux-core as git submodule

coral2.rst, index.rst
The CORAL2 systems Lassen, Sierra, and Summit all require extra
components to integrate properly with Flux.  This new section describes
the two Lmod packages and various extra arguments required to get Flux
bootstrapped under jsrun and Spectrum MPI running under Flux.
Closes #18
=> coral2: add docs on launching Flux and Spectrum MPI jobs

coral.rst
The Sierra and Summit systems are CORAL systems.  Frontier and El
Capitan are the CORAL2 systems.
Credit to @tgamblin and Bilel Hadri for catching the mistake.
=> CORAL: remove the 2 suffix

quickstart.rst
As mentioned in #26:
> As noted in #25, example output in the quickstart guide uses real usernames, and thus usernames may not match across all examples.
@SteVwonder had already changed the usernames to `user1` in PR #25, but since the issue wasn't closed, I went ahead and changed the usernames in **quickstart.rst** to `fluxuser`.
There was also a small formatting issue in **quickstart.rst** where the code block following the 'Build flux-sched' instruction was not rendered properly because of an extra colon, so I went ahead and removed the extra char and stacked another commit on top of this PR.
=> quickstart.rst: unify all example output under a common username

quickstart.rst
recent changes to the docker images will auto-start a Flux instance in
the container if no command is provided
removes the `bash` command and includes examples of running jobs within
the container
this PR should only go in after https://github.com/flux-framework/flux-sched/pull/648 is merged
=> quickstart: update docker run instructions

conf.py, debugging.rst, index.rst, spell.en.pws
- Add doc on how to debug parallel jobs using TotalView
Introduce basic TotalView commands
for launch and attach mode
- Add ways to improve Flux's own internal exec
events within TotalView.
- Add known issues section to document
current limitations.
- Increase flux-core version number to 0.19.0
=> Add parallel debugging section 

batch.rst, index.rst, spell.en.pws
Add doc on how to submit your batch scripts with
some examples.
Use single-user Flux examples with a caveat that
same commands and techniques will also work at the system level.
=> Add Flux batch job HOWTO section

.github/workflows/main.yml, coral.rst
The latest Spectrum version requires a flag to disable the loading of a pami gpu library that segfaults when not run directly under jsrun (e.g., when Flux is bootstrapping).
Also include the instruction to load our `flux` module to access side installs of Flux.
I manually tested the updated instructions on both Lassen and Summit.  I don't think the `-disable_gpu_hooks` flag does anything on Summit since they are running an older Spectrum version, but thankfully, `jsrun` and Spectrum MPI do not complain when it is provided.
=> Update CORAL-specific instructions for latest Spectrum updates

adminguide.rst, index.rst, quickstart.rst, spell.en.pws
This is a *very* rough draft of a Flux admin doc meant as a reference for sysadmins managing system instances of Flux.
I basically cribbed completely from @garlick's previous work, starting with the outline proposed in #58, and cut-and-pasting a lot of text from the [Small system instance setup](https://github.com/flux-framework/flux-core/wiki/Small-system-instance-setup) wiki page.
I wanted to post this draft so people could comment early if the guide isn't on the right track.
=> add Flux Administrator's Guide

.readthedocs.yml, requirements.txt
Problem: RTD switched from primarily configuring builds via their web interface to using version control yaml files. Additionally, the build is currently using an old version of Pygments that does not support syntax highlighting of toml.
Solution: kill two birds with one stone by adding an RTD top-level config yaml that requests python 3.7 and then request a newer version of Pygments (which requires py3.5+).
Closes #64
=> readthedocs: add top-level ReadTheDocs (RTD) config yaml file

adminguide.rst
I made a pass over the admin guide and tried to add some more things that the sys admins will want to be aware of when working with 0.20.0.
=> admin guide: add more 0.20.0 restrictions

adminguide.rst
Update all notes/warnings that refer to the specific version.
Shorten a couple of section names to make them more general and
clear.
Fix whitespace.
=> adminguide: update for release 0.21.0

adminguide.rst
Rename the "Resource exclusion" section to "Resource configuration",
and add an explanation of the 'path' key and an example command line
for generating R with flux-R.
=> adminguide: explain how to configure resources

batch.rst
Fix a slightly confusing typo discovered by a user.
=> batch.rst: typo fix

conf.py, index.rst
Adds a subsection to `index.rst` that references the new flux-workflow-examples docs.
Improves the section and reference titles for flux-core and flux-rfcs.
Closes #75, #76
Depends on https://github.com/flux-framework/flux-core/pull/3365
=> Add Workflow Examples and Improve Section/Reference Titles

adminguide.rst, spell.en.pws
Add a section introducing the flux-resource `status` and `list` commands, so that admins are at least aware of these tools and their potential use.
=> adminguide: add description of flux-resource status and list commands

quickstart.rst
Problem: quick start guide instructs users to run flux keygen,
but as of flux-core 0.22.0, this is no longer necessary.
Drop this text.
=> quickstart: drop flux keygen

contributing.rst
Now that we are switching over from Travis CI to Github Actions,
remove the reference to Travis in contributing.md.
=> contributing: remove reference to travis CI due to switch

coral.rst
Remove the no longer needed Flux-specific Spectrum MPI module and replace the old test for CUDA-enabled hwloc with `flux resource list`
Closes #86 #71
=> coral: update MPI and GPU sections

adminguide.rst
Replace errant `/` with `.` for file extension name
=> adminguide: fix typo in toml path

faqs.rst, spell.en.pws
Problem: some versions of OpenMPI work with Flux and some do not,
and it would be helpful to users to know which ones should work.
Add a FAQ entry.
=> faqs: what versions of OpenMPI work with Flux?

faqs.rst
Problem: faq states that 4.0.2+ works, but also says a bug
affected versions _through_ 4.0.2.
I think the bug affects 4.0.1 but not 4.0.2, so state that the
bug affects versions through 4.0.1.
=> faqs: change openmpi version number 4.0.2 -> 4.0.1

quickstart.rst
It sounds like (per https://github.com/flux-framework/flux-core/issues/3599 & a conversation with @vchuravy) you're trying to phase out `flux start --size=<N>`.
You might also want to change an earlier example in `quickstart.rst` `docker run -ti fluxrm/flux-sched flux start --size 4`, but I wasn't sure.
=> Remove `--size` in quickstart.rst

adminguide.rst, spell.en.pws
This updates some references to earlier flux-core versions to the one we are releasing today (0.29).
It also adds a little troubleshooting subsection for the overlay network that highlights the new `flux overlay` command.
=> admin guide: update for flux-core 0.29

.gitignore, conf.py, coral.rst, requirements.txt, spell.en.pws
The latest installations of Flux are much easier to use on the CORAL systems.  Update the documentation accordingly.
WIP while I wait to test the streamlined instructions on a multiple node allocation on Summit (been waiting in debug queue all day).
=> Update CORAL systems based on latest install

coral.rst
Problem: Our document currently notes that
`--smpiargs="-disable_gpu_hooks"` should be used when
users are encountering segmentation faults in the OS’s glibc.
But I find that this bug can emerge for most of our
users who use a typical shell environment (e.g.,` tcsh`).
Add this option as our recommended default
launch line. There is really no harm in adding it
except the launch line becomes a bit longer.
=> coral: add --smpiargs="-disable_gpu_hooks" to jsrun line

adminguide.rst
flux-core v0.30.0 has been released and has all the same caveats
as v0.29.0, so update references in the admin guide.
=> adminguide: update v0.29 references to v0.30

coral.rst, requirements.txt
This is an attempt to fix the problems rendering bullet lists described in #104.  I couldn't reproduce it locally, and for some reason github actions aren't kicking off in my local fork, so trying this as a PR.
=> fix list rendering and Pygments warning

faqs.rst
Problem: the FAQ recommends setting _rundir_ to relocate the sqlite database file, but this can cause problems with UNIX domain sockets as noted in flux-framework/flux-core#3925.
Update this FAQ entry and add some other information that might prove helpful.
Plus some other cleanup in this rst file.
=> faqs: update sqlite redirection instructions + misc cleanup

adminguide.rst, spell.en.pws
This PR adds a new section to the bottom of the Admin Guide that details setup instructions for the flux-accounting database and multi-factor priority plugin as well as configuration of the automatic update scripts for fairshare and job usage values.
=> admin guide: add flux-accounting setup section

faqs.rst
Problem: Users just starting with `flux mini bulksubmit` may be
confused that it waits on stdin by default, apparently hanging.
Add a FAQ entry to which we can point users or they perhaps discover
on their own.
=> Add short FAQ entry for `flux mini bulksubmit` "hangs"

adminguide.rst
Problem: The admin guide refers to v0.31.0, includes a warning that no longer applies, and shows outdated `flux overlay status` arguments in an example.
Update guide for v0.32.0.
=> update admin guide for flux-core v0.32.0

.mergify.yml, adminguide.rst
This is a small collection of fixes:
* update mergify config to use queues since strict merge is no longer supported
* Fix an incorrect path to imp config in admin guide
* update output of `flux overlay status` in admin guide (this one may be premature, but I went ahead and updated output while I was thinking about it) Happy to drop this one for now.
=> update mergify config and small admin guide fixes

adminguide.rst
This PR updates flux-core version refs from 0.32.0 to 0.33.0.
Also, it turns out the job prolog/epilog section was pretty confusing, so the description has been expanded somewhat in hopes of alleviating any confusion between job vs job-manager prolog/epilog,  IMP "run" support, and the `/etc/flux/system/{prolog,epilog}.d` directory. (Unsure if it is any clearer now)
=> adminguide: update flux-core version references, clarify prolog/epilog documentation

adminguide.rst
Problem: the admin guide gives instructions for manually installing
a Flux system instance, but this is unlikely to be an acceptable
practice at most sites and just decreases the signal to noise ratio
in the document.
Drop the installation description and add a 'note' box directing
would-be Flux package maintainers to open an issue for assistance.
=> adminguide: drop manual install instructions

.mergify.yml
Problem: The .mergify.yml had a line that was off by one space,
and thus could not be parsed as YAML.
Fix the invlalid YAML, also move some conditions back to
pull_request_rules.
=> mergify: fix mergify config

adminguide.rst, conf.py
This sprinkles some man page domainrefs throughout the admin guide, including to the new section 5 config pages.
=> adminguide: add man page references

adminguide.rst
As noted in flux-framework/flux-core#4067, the admin guide `[bootstrap]` example doesn't match the text.  Fix that.
=> adminguide: fix bootstrap example

conf.py, index.rst
This PR adds a link to the new flux-security man pages, as well other configuration bits to make reference flux-security docs possible in this high-level documentation repo.
=> add link, refs, and intersphinx config for flux-security

adminguide.rst
Add references to the new flux-security man pages from the top level landing doc, as well as the flux admin guide.
=> add flux-security man page references

adminguide.rst
Bump the flux-core version number, and add a section for configuring TCP keepalives.
=> adminguide: update for flux-core 0.35.0

conf.py, index.rst
This PR simply adds some links from our top-level docs to the newly added stub for flux-sched/fluxion documentation.
=> add flux-sched links to main readthedocs site

adminguide.rst
Problem: the [archive] configuration example uses integer seconds where FSD is required.
Update example.
This was noted in flux-framework/flux-core#4163.
=> adminguide: fix [archive] TOML example

faqs.rst
Problem: instructions for relocating content.sqlite refer to
'content.backing-path', which is no longer a valid broker attribute.
Update the instructions to suggest setting 'statedir' and reword
instructions to be more clear now that the database file path itself
cannot be explicitly set.
=> faq: update content.sqlite instructions

quickstart.rst
Problem: the `flux-hwloc` command is being removed (flux-framework/flux-core#4262) but this command is referred to several times in the quickstart guide.
Substitute other commands.
=> quickstart: remove references to flux-hwloc

coral.rst
Problem: configure argument for pmix has a typo
Fix typo
=> coral: fix typo

adminguide.rst, coral.rst
This PR updates the admin guide for flux-core v0.40.0.
I haven't read through the guide for any other updates, but simply updated 0.39.0 to 0.40.0.
Others should feel free to push directly here if they find any other updates that need to be made.
=> adminguide: updates for v0.40.0

adminguide.rst, spell.en.pws
Update the flux-core release mentioned in the admin guide to v0.42.0 and add limits, defaults, and kvs checkpiont to the example config.  Merge should probably be delayed until that release is tagged.
=> adminguide: update for flux-core 0.42.0 release

adminguide.rst
Problem: example TOML config is improperly formatted.
Insert a leading space where one was missing.
=> adminguide: fix formatting error

flux-accounting-guide.rst, index.rst
As the flux-accounting project continues to mature and become more of a part of system-instance Flux, it would be nice to have more documentation about the specifics of flux-accounting, such as database administration, job usage and fair-share information, the multi-factor priority plugin, and more. It might also be nice if this documentation was easy to locate alongside the other Flux components.
---
This is a small [WIP] PR that adds a separate page in flux-docs that adds more details about the flux-accounting sub-project. For the purposes of keeping this PR somewhat simple (and hopefully easy to review!), I've only added one sub-section: a sub-section that outlines basic database administration and a glossary. 
I've written this guide with the intended audience of an administrator …
=> docs: add a flux-accounting section

faqs.rst
The hyperlink to flux-tree no longer works on the FAQ page after flux-framework/flux-sched#956, which moved `flux-tree` to the test suite and changed paths in the repo. 
---
This PR removes the hyperlink to the `flux-tree` source code since it is not available except in the source repo, and instead makes mention of `flux mini submit` and `flux mini bulksubmit`. It also adds a hyperlink to the `flux-mini` manual page.
Fixes #151
=> faqs: remove hyperlink to `flux-tree`, reference `flux-mini` instead

adminguide.rst
Problem: the example flux system configuration does not
call the feasibility validator plugin, so jobs with unsatisfiable
resource requests are terminated with an exception rather than
being rejected at submit time.
Add [ingest] to the example.
=> adminguide: add [ingest] table to example config

adminguide.rst
Problem: the adminguide recommends installing flux-sched
but omits configuration from the example config file.
Add example and man page references.
=> adminguide: add fluxion config

faqs.rst, spell.en.pws
The FAQ didn't have any categories so I added a General category for most everything we have now, and another for MPI, and added some new entries to the MPI section based on our fun with mvapich and openmpi this past week.
A couple of other entries were updated, and one on F58 encoding issues was added.
=> faqs: update based on early flux rollout on production systems

faqs.rst
The FAQ entry titled "How do I mimic Slurm's job step semantics" probably will leave users with more questions than answers.
Take a crack at expanding this explanation and reorienting the curious towards Flux's way of doing things.
=> faqs: update job steps entry

faqs.rst
Problem: the "how do I efficiently launch a large number of jobs"
FAQ entry refers to the outdated workflow examples, and doesn't
provide a lot of useful info.
Expand this section, and add the now important suggestion to
run jobs in a sub-instance, not the system instance.
=> faqs: rework "launch large number of jobs" entry

faqs.rst
Problem: the faqs entry "How do I efficiently launch a large
number of jobs" does not mention redirecting stdio to files, or
excluding rank 0 from scheduling either of which may be appropriate
in some cases.
Add bullets for these suggestions.
=> faqs: add more tips for launching many jobs

flux-accounting-guide.rst
While working on #150, a suggestion was made to add a brief citation to explain the need for adopting similar terms to Slurm's open source accounting docs in order to meet local management requirements.
---
This PR adds a notice about the similarities in both terms and concepts between flux-accounting and Slurm at the bottom of the guide, with links to both the Slurm documentation as well as the GNU General Public License documentation.
Fixes #160
=> flux-accounting guide: add citation to Slurm

adminguide.rst
This PR adds a reminder in the Flux Accounting section in the Administrator's Guide to update the database on a system after upgrading to a newer version of flux-accounting where a DB already exists, as tables and columns could be added or removed when moving to a newer version.
=> adminguide: add reminder to update DB after flux-accounting version upgrade

adminguide.rst
@woodard was trying to set up a heterogeneous system instance of Flux and noticed there are no examples of how to generate R in this case.
Add a note about nodes with differing numbers of cores and an example of generating R with multiple `flux R encode`
=> adminguide: add example for heterogeneous nodes 

flux-accounting-guide.rst
This is a small PR that adds a new section to the flux-accounting guide which gives details about the multi-factor priority plugin, the factors it uses to calculate job priorities, and the job limits it currently enforces. It references the various job states defined in [RFC 21](https://github.com/flux-framework/rfc/blob/master/spec_21.rst) when talking about the job limit enforcement.
=> accounting: add multi-factor priority plugin section

adminguide.rst
This PR adds a small note to the flux-accounting section in the Administator's Guide about correctly setting permissions and ownership for both the flux-accounting DB and the directory it resides in after it is installed on a system. It includes a reference to the SQLite documentation in this note about read/write permissions.
=> admin guide: add flux-accounting DB permissions note

adminguide.rst, spell.en.pws
This updates the caveats for the just-released flux-core 0.44.0, adds a subsection describing how to set up queues, and adds some background to the overview section.
=> adminguide: update for flux-core 0.44.0, add background

adminguide.rst, flux-accounting-guide.rst
Tell me what you think about this @cmoussa1.  I thought it might be better to have all the accounting information in one manual rather than splitting it between the admin guide and the accounting guide, so this consolidates it in the accounting guide. This also adds an intro section which seemed necessary to establish some context.
(Please read the intro carefully and make sure I'm not misrepresenting the project or misusing the terminology!)
=> move accounting section of admin guide into accounting guide

adminguide.rst, spell.en.pws
Problem: the Software Components section missed a few component types.
Add short descriptions for connectors, uri resolvers, validator plugins, and frobnicator plugins.
=> adminguide: add more plugin types to components section

adminguide.rst
Problem: the Overview architecture sub-section opens with a sentence about the Flux broker executable, when what is trying to convey is the notion of a Flux instance as a collection of brokers.  It seems like an odd way to begin.
Reword that sentence to lead with the "flux instance" term. Also reword another sentence in that section that seemed awkward.
=> adminguide: minor tune-up of overview architecture

adminguide.rst, spell.en.pws
Problem: the admin guide does not mention the flux-pam package.
Add flux-pam to the package list, and add a brief section on configurign it (mostly just a placeholder).
Rename the exsiting "Configuring PAM" section to be more specific to the IMP PAM config.
=> adminguide: add flux-pam

adminguide.rst, conf.py, spell.en.pws
Problem: we really want people to capture stack traces if the rank 0 broker crashes, but the admin guide says nothing about configuring a system to capture core dumps.
Add a System Prerequisites subsection that talks about core capture and a note about reporting broker crashes.
=> adminguide: add a blurb about core dumps

glossary.rst, index.rst, quickstart.rst
The documentation site contains terms, both Flux-specific and not, that might be unclear to users who are reading the site and/or about Flux for the first time. It was discussed in #185 that the site might benefit from having a page dedicated to explaining in slightly more detail some of the terms, concepts, and acronyms mentioned throughout our site which may be unfamiliar to users who are reading about Flux (or resource managers, HPC concepts, etc.) for the first time.
---
This is a small PR meant to kick off the start of a **Glossary** page for our docs site, a page that explains in more detail these terms and concepts. Mention of this new page is referenced at the top of the **Quick Start** guide for users who might want to look back at this page as they read throughout the guide and …
=> docs: add a new "Glossary" section

tutorials/commands/index.rst, tutorials/commands/ssh-across-clusters.rst, tutorials/index.rst, tutorials/lab/coral.rst
This uses a proxy jump in the ssh config.
I don't have this working yet, but wanted to open the PR to clearly lay out what I'm doing (so we can see what I'm doing wrong).
Update: all is working! I was missing `export FLUX_SSH=ssh` and then `--force`
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> add tutorial to connect to flux between clusters

tutorials/commands/flux-mini-submit.rst, tutorials/commands/index.rst
This is a small [WIP] PR built on top of #192 that adds a tutorial on how to submit jobs to Flux. It leverages the steps outlined in the [job-submit-cli](https://github.com/flux-framework/flux-workflow-examples/tree/master/job-submit-cli) workflow example. I ran the commands outlined in an updated Docker container to make sure they still worked (I could always use another set of eyes to double-check me, though 😉).
Future expansion of this specific tutorial could include a chapter on how to submit jobs to Flux using it's job submission API. But for the purposes of getting some short tutorials out there, I've just included the command-line portion.
=> tutorials: add a tutorial on submitting jobs to Flux

glossary.rst
Some were listed in #186, some weren't.  Just trying to fill it out more.
=> Add more glossary terms

faqs.rst, jobs/batch.rst
"sub-instance" should not be hyphenated.
=> Remove hyphen in "sub-instance"

tutorials/commands/ssh-across-clusters.rst
Problem: The code blocks where syntax highlighted to 'sh', but they should just be 'console' output.
Update all code blocks to be 'console' color outputted.
---
@vsoch - agree?  I just noticed some weird colorization in the console output.
=> tutorials: correct code blocks colorization

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/dev-requirements.txt, README.md
This is step 1 for adding dynamically generated python tutorials! This dev container will allow us to run flux alongside the docs generation.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> add basic dev container to run flux and generate docs alongside

tutorials/commands/flux-mini-submit.rst, tutorials/commands/index.rst, tutorials/commands/ssh-across-clusters.rst
originally in #193, we intended to be in the `flux mini submit` tutorial but I guess we forgot about it.  I didn't think it was worthwhile to separate it out to a new tutorial b/c its so small and highly related to `flux mini submit`.  So I put it in there.
Lots of mini cleanups along the way too.
=> tutorials: add flux mini run tutorial/example

tutorials/commands/flux-mini-submit.rst
Problem: In the flux mini submit tutorial, there is no information on how to view stdout/stderr of a job.
Add a pointer for users to go to "flux job attach" for more information.
----
Note, for after https://github.com/flux-framework/flux-core/pull/4936 is merged
=> tutorials: add pointer to "flux job attach"

faqs.rst, glossary.rst, guides/admin-guide.rst, jobs/batch.rst, jobs/debugging.rst, jobs/hierarchies.rst, quickstart.rst, tutorials/commands/flux-submit.rst, tutorials/commands/index.rst, tutorials/commands/ssh-across-clusters.rst, tutorials/lab/coral.rst, tutorials/lab/coral2.rst
Here's a batch of updates to change references to the flux-mini commands to their new names which will appear in flux-core v0.39.0.
=> deprecate flux-mini

.devcontainer/Dockerfile
Problem: permissions are written as root in the current devcontainer
Solution: run them as the vscode user with uid/gid 1000
This is the same fix applied to the flux-core container - I also tested it out (and doing things with sudo) and it seems good!
=> docker dev environment fix permissions

.github/scripts/check_diff.py, auto_examples/index.rst
I think @chu11's simple PR failed because we are missing the sys import! Let's get this change in.
=> fix bug with check_diff.py sys import missing

jobs/batch.rst
Problem: One reference to "mini batch" lingered, it's just batch now.
Rename mini batch to batch.
=> jobs: remove lingering reference to mini batch

index.rst, quickstart.rst
Problem: the comparison table is highly useful, but hidden under a section of the FAQ and hard to find.
Solution: add it as a navigation tab on the top (the rationale that some will come to the docs explicitly looking for it) along with as a link in the first line of the quickstart.
This has been a thought lingering on my mind for a few months, and after someone in the slack had the same trouble to validate my concern, I think we want to better expose our comparison table. For this PR, I've added it exposed in two places:
1. At the very top as its own navigation heading
We aren't best using these navigation headings (we only have two!) and I think a substantial number of users coming to the site are coming explicitly to answer the question "How does this Flux tool compare to..." so it …
=> expose flux comparison table

tutorials/lab/coral2.rst, tutorials/lab/index.rst, tutorials/lab/rabbit.rst
Updates and simplifies the CORAL2 documentation to remove a lot of outdated configuration information. Also adds documentation about how to use rabbits.
The CORAL2 docs I don't expect anyone to look at really, except maybe I can point some admins to it occasionally. The rabbit page I expect to be used much more frequently.
=> Rabbit usage documentation

tutorials/containers/index.rst
These tutorials come with a lot of supporting files and context, so I think it makes sense to reference them instead of duplicating, that way people can open issues there, request more examples, easily clone to get started and we don't need to update in two places.
I added a cleaned up "replicas" example this morning.
=> add docker-compose container tutorials

tutorials/lab/coral2.rst
Since I've had to debug MPI on coral2 lately I thought I'd do a little work on the Cray MPICH info in the coral2 guide.  This is probably a bit rough and I'm very open to suggestions on reverting my changes to the original, restructuring, or whatever, so let's consider it a WIP.
=> coral2: expand MPI section

guides/admin-guide.rst
@grondo and I both ran into shells printing:
```
flux-shell[0]:  WARN: rlimit: nproc exceeds current max, raising value to hard limit
```
and it took a little sleuthing to figure out what was going on.  Add a small trail of bread crumbs to the admin guide for next time.
=> admin guide: provide helpful debugging info for PAM limits

guides/learning_guide.rst
fix small typo in learning guide furing -> during
=> Small typo "During"

tutorials/commands/flux-jobs.rst
Problem: The author is bad at English, "lets" -> "let's" when it means "let us".
Solution: Fix English.
=> tutorials/flux-jobs: Fix invalid contractions

index.rst
Problem: we got feedback that the frontpage of the docs is not super useful for providing information about flux, namely what makes it special.
Solution: add the flux "killer feature" and link to the comparison table
=> improve content on front page

guides/admin-guide.rst, requirements.txt
Problem: Flux requires local clocks to be synchronized across the cluster, but this is not mentioned in the Admin Guide.
For example
- job-ingest sets `t_submit` to the local time
- flux_job_timeleft() returns expiration relative to the local time
- Flux logs are time stamped at origin
Add a note to the section on prerequisites.
=> admin: add note about clock synchronization

jobs/batch.rst
Someone complained that when they searched "start Flux interactively" they got a reference to starting Flux under Slurm `salloc` in a section about batch jobs.
Since this didn't make much sense, I wanted to remove this section. I didn't want to go into too much cleanup here, so I just went through the `jobs.batch.rst` docs and removed erroneous or outdated information, and corrected an example.
=> jobs: cleanup jobs/batch.rst

.readthedocs.yml
Problem: the readthedocs config is missing os
Solution: update the format.
Criteria for merge are a successful readthedocs build, since there are no other changes. This is a response to #256 where the build failed due to missing build.os key in .readthedocs.yaml.
=> fix: readthedocs config

tutorials/commands/flux-submit.rst
Problem: The flux-submit tutorial gives an example that uses --name to set the job name, but no such option exists.
Correct --name to --job-name.
=> tutorials: fix incorrect option in flux-submit tutorial

guides/admin-guide.rst
Problem: There is a statement in the admin guide that it is good practice to use property names that match the corresponding queue name, but no reason for this practice is given.
Explain that queue properties do not need to match the queue name, but note that it is good practice because it allows flux-resource list to suppress these duplicate names in is output.
=> admin-guide: clarify queue property name requirements

guides/accounting-guide.rst
The flux-accounting guide has a table which lists all of the tables in the flux-accounting database, but the schema has been updated to have a couple new tables.
---
This PR updates the flux-accounting guide to include these new tables.
=> accounting-guide: update description of DB tables

guides/accounting-guide.rst
flux-accounting doesn't have a clear definition for fair-share and its place in the priority plugin in terms of calculating a job's priority in the Accounting Guide.
---
This PR adds 'fair-share' as a term in the Glossary section with an expanded definition.
It also makes the "Glossary" section a reference-able one in the flux-accounting guide so that when fair-share is mentioned in the **Multi-Factor Priority Plugin** section, the expanded definition can be easily linked to.
~~_leaving as [WIP] for now because I'm having trouble getting Sphinx installed on my recently updated Mac and can't build it locally 😔_~~
=> glossary: add expanded definition for 'fair-share'

jobs/debugging.rst
This adds the helpful TotalView doc updates by @suzannepaterno from #251 without the merge commits. I was unable to force push to the other PR.
=> Update documentation for using TotalView with Flux

guides/accounting-guide.rst
flux-accounting has a new service that accepts `flux account` commands that interact with the flux-accounting database and can be controlled with `systemd`, but there are no setup instructions on how to get it going in the flux-accounting guide on our docs site.
---
This PR adds a couple of small fixes along with a set of notes on installing and setting up the flux-accounting service in the flux-accounting guide. Since this new addition to documentation will be required _as a result of_ the new flux-accounting release coming up in a few days, I will leave this is as [WIP] until the release has been finalized. Feel free to take a look at my changes proposed here in the meantime, though, in case there is any feedback. 👍
Fixes #215
=> flux-accounting guide: add setup instructions for new flux-accounting service

tutorials/lab/coral2.rst
Problem: there is no documentation for how to configure Fluxion for use with rabbits.
Add a couple of sentences of detail to the coral2 page.
=> coral2: add instructions for building rabbit JGF

auto_examples/index.rst, tutorials/lab/coral.rst
Problem: the CORAL interactive tutorial uses the username "elvis" in all places but one.
Solution: make the document consistent by removing the last reference to "hobbs17" and replacing with "elvis".
=> tutorials: make CORAL example consistent

faqs.rst
I put and/or because it sounds like you need one on Azure (or possibly both) and the other on LC resources. Could differ at other centers too depending on if pmix is the default.
=> faq: update openmpi faq to reference pmix

tutorials/lab/rabbit.rst
Problem: HPE has documentation about the usage of #DW directives that is much more detailed and formal than the documentation given in this repo.
Remove the duplicated docs and link to the HPE documentation.
@bdevcich @ajfloeder want to make sure this is OK with you.
=> coral2: link to HPE rabbit docs

tutorials/lab/rabbit.rst
Dumb change but pointing to 'latest' wasn't an option when #275 was merged, it only became an option when HPE published a new release two hours ago.
=> coral2: update HPE rabbit docs link

tutorials/lab/rabbit.rst
Problem: flux-core PR github.com/flux-framework/flux-core/pull/6238 introduced the `-S` option as shorthand for `--setattr`, and users will most likely prefer using `-S`, but only `--setattr` is described in the documentation.
Change the documentation to list both options and make the examples use `-S`.
=> coral2: change rabbit docs to use -S flag

tutorials/lab/rabbit.rst
Problem: there is no documentation for the rabbit_datamovements KVS entry.
Add docs.
=> rabbit: add docs on rabbit_datamovements

projects.rst
flux-accounting is not listed as a subproject on the Projects page on the flux-framework documentation site.
---
Add flux-accounting as a project and point to its documentation on ReadTheDocs.
=> projects: add flux-accounting as subproject

.github/workflows/main.yml, conf.py, faqs.rst, jobs/batch.rst, jobs/debugging.rst, quickstart.rst
Problem: there are some broken links in our docs.
Fix them.
=> Fix broken links and add linkcheck back to CI

contributing.rst
The Flux projects have very robust and powerful test environments, but there isn't any documentation on how to leverage this test environment for new developers or people who want to contribute to the project for the first time.
---
This PR adds a "Testing" section to the **Contributing** document on how to run tests within a Flux project and combine it with other tools such as `valgrind`. I pretty much just copied the contents from #89 and formatted it into its own subsection. Feel free to push to this branch if there are other tips not included there but could be useful.
Fixes #89
=> contributing: add testsuite tips section

tutorials/lab/rabbit.rst
Problem: flux-coral2 supports preset DW strings, but they aren't described in the rabbit docs.
Add documentation.
=> rabbit: add docs on preset #DW strings

.github/workflows/main.yml
Problem: recently, our github workflow for spelling and
linkcheck got confused between pre-installed debian packages
and python's pip installed packages.
Just ignore the debian packages. Install our own. It doesn't
seem to take much longer.
```
-I, --ignore-installed
Ignore the installed packages, overwriting them. This can break your system if the existing package is of a different version or was installed with a different package manager!
(environment variable: PIP_IGNORE_INSTALLED)
```
From: https://pip.pypa.io/en/stable/cli/pip_install/
=> github: add `--ignore-installed` to `pip install` of requirements 

conf.py, faqs.rst
Problem: There's no advice for how to run batch jobs that are resilent to node failure.
Add an entry in the FAQ.
=> faq: add entry about reslient batch jobs

conf.py, guides/learning_guide.rst
I'm a little confused on why the typo wasn't picked up by aspell or typos, whichever we're running here. When I ran typos by hand nothing unexpected showed up.
The double copyright might also be a problem in all our framework repos that use RTD for docs.
Closes #299
=> Minor doc fixes

conf.py
The copyright dates on flux-docs specifies a range of years (2014-2023), but this copyright is still active.
---
This PR removes 2023 from the copyright and just leave the starting year (which is consistent with the copyright dates throughout the various flux projects).
=> `conf.py`: remove 2023 from copyright date range

conf.py
There is an extra `.append()` call to add the `"sphinx_immaterial"` extension.
---
This PR just removes the extra call.
=> `conf.py`: remove double `.append()` call

conf.py, faqs.rst, quickstart.rst
@ryanday36 noticed a typo in the FAQ entry on using `statedir`. Additionally, it was suggested that adding some example errors would be helpful here.
=> improve FAQ entry about filling up `/tmp`

faqs.rst, quickstart.rst, tutorials/commands/flux-jobs.rst
Problem: `flux job cancel` has been deprecated for awhile, but a few references remain in the docs.
Update calls to `flux job cancel` to use `flux cancel` instead.
=> update references to `flux job cancel`
